# Generated by Django 4.2.5 on 2023-10-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_roll', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='student_images/')),
                ('university_name', models.CharField(max_length=100)),
                ('semester1_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semester2_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semester3_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semester4_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semester5_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semester6_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semester7_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semester8_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
