# Generated by Django 4.2.5 on 2023-10-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0002_alter_student_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
