# Generated by Django 4.2.5 on 2023-10-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ENGLISH', 'ENGLISH'), ('CE', 'CE'), ('BBA', 'BBA'), ('MECHANICAL', 'MECHANICAL')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='university_name',
            field=models.CharField(default='University Of Global Village, Barishal', max_length=100),
        ),
    ]
