# Generated by Django 4.2.5 on 2023-10-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0007_student_cgpa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
